name: avtraj

channels:
  - fluorescence-tools
  - tpeulen
  - conda-forge
  - defaults

dependencies:
    - python=3.7
    - mdtraj
    - pyyaml
    - numba
    - labellib
    - sphinx
    - sphinx_rtd_theme
    - coverage
    - nose
